opensandbox-controller:
  controller:
    logLevel: info
    replicaCount: 1

opensandbox-server:
  configToml: |
    [server]
    host = "0.0.0.0"
    port = 80
    api_key = "dev-opensandbox-key"

    [log]
    level = "INFO"

    [runtime]
    type = "kubernetes"
    execd_image = "sandbox-registry.cn-zhangjiakou.cr.aliyuncs.com/opensandbox/execd:v1.0.17"

    [kubernetes]
    kubeconfig_path = ""
    namespace = "opensandbox"
    informer_enabled = true
    informer_resync_seconds = 300
    informer_watch_timeout_seconds = 60
    snapshot_create_timeout_seconds = 900
    workload_provider = "batchsandbox"
    batchsandbox_template_file = "/etc/opensandbox/example.batchsandbox-template.yaml"

    [egress]
    image = "sandbox-registry.cn-zhangjiakou.cr.aliyuncs.com/opensandbox/egress:v1.0.12"
    mode = "dns+nft"

  server:
    image:
      repository: sandbox-registry.cn-zhangjiakou.cr.aliyuncs.com/opensandbox/server
      tag: v0.1.14
    replicaCount: 1
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
    gateway:
      enabled: true
      host: sandbox.localhost
      gatewayRouteMode: header
      image:
        repository: opensandbox-ingress
        tag: local
      replicaCount: 1
      dataplaneNamespace: opensandbox
      providerType: batchsandbox
      logLevel: info
      resources:
        limits:
          cpu: "500m"
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
