opensandbox-controller:
  namespaceOverride: ${NAMESPACE}
  controller:
    logLevel: info
    replicaCount: 1
    image:
      repository: ${HARBOR}/${HARBOR_PROJECT}/mirror/opensandbox/controller
      tag: "v0.2.0"
    snapshot:
      imageCommitterImage: ${HARBOR}/${HARBOR_PROJECT}/mirror/opensandbox/image-committer:v0.1.1

opensandbox-server:
  namespaceOverride: ${NAMESPACE}
  configToml: |
    [server]
    host = "0.0.0.0"
    port = 8080
    api_key = "${OPEN_SANDBOX_API_KEY}"

    [log]
    level = "INFO"

    [store]
    type = "sqlite"
    path = "/tmp/opensandbox/opensandbox.db"

    [runtime]
    type = "kubernetes"
    execd_image = "${HARBOR}/${HARBOR_PROJECT}/mirror/opensandbox/execd:v1.1.0"

    [kubernetes]
    kubeconfig_path = ""
    namespace = "${NAMESPACE}"
    informer_enabled = true
    informer_resync_seconds = 300
    informer_watch_timeout_seconds = 60
    snapshot_create_timeout_seconds = 900
    workload_provider = "batchsandbox"
    batchsandbox_template_file = "/etc/opensandbox/example.batchsandbox-template.yaml"

    [egress]
    image = "${HARBOR}/${HARBOR_PROJECT}/mirror/opensandbox/egress:v1.1.7"
    mode = "dns+nft"

  server:
    port: 8080
    image:
      repository: ${HARBOR}/${HARBOR_PROJECT}/mirror/opensandbox/server
      tag: v0.2.3
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi
    gateway:
      enabled: true
      host: ${SBX_DOMAIN}
      gatewayRouteMode: header
      image:
        repository: ${HARBOR}/${HARBOR_PROJECT}/mirror/opensandbox/ingress
        tag: v1.0.10
      replicaCount: 1
      dataplaneNamespace: ${NAMESPACE}
      providerType: batchsandbox
      logLevel: info
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: "500m"
          memory: 512Mi
