apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: harakiri-web
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/part-of: harakiri-security
spec:
  host: ${WEB_HOST}
  to:
    kind: Service
    name: harakiri-web
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: harakiri-api
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/part-of: harakiri-security
spec:
  host: ${API_HOST}
  to:
    kind: Service
    name: harakiri-api
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: keycloak
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/part-of: harakiri-security
spec:
  host: ${AUTH_HOST}
  to:
    kind: Service
    name: keycloak
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sandbox-wildcard
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/part-of: harakiri-security
spec:
  host: wildcard.${SBX_DOMAIN}
  wildcardPolicy: Subdomain
  to:
    kind: Service
    name: opensandbox-ingress-gateway
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
