import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import sharp from 'sharp';
import { exec, fileHash, json, root, workspace, writeJson } from './io.js';
import { uiTourSchema } from '../src/data/ui-tour-schema.js';
import { workflowCaptions } from './workflow-captions.js';
import { uiProductTourChapters, uiProductTourSeconds } from '../../web/src/ui-product-tour.js';
import { tourTutorialHtml } from './tour-tutorial.js';
import { writeDemoIndex } from './demo-index.js';

const source = join(workspace, 'public/ui-product-tour');
const tour = uiTourSchema.parse(await json(join(source, 'tour.json')));
for (const clip of tour.clips) assert.equal(await fileHash(join(source, clip.file)), clip.sha256);
const target = join(root, 'apps/web/public/demos/ui-product-tour');
const staging = join(root, 'docs/artifacts/demo/ui-product-tour/render');
await mkdir(target, { recursive: true });
await mkdir(staging, { recursive: true, mode: 0o700 });
console.log(`Rendering ${uiProductTourSeconds}s of full-frame UI at 1920x1080 / 30 fps.`);
await exec('pnpm', ['exec', 'remotion', 'render', 'src/index.ts', 'ui-product-tour', join(staging, 'render.mp4'), '--codec=h264', '--crf=24', '--concurrency=4', '--log=error'], { cwd: workspace, timeout: 2400000, maxBuffer: 12 * 1024 * 1024 });
await exec('ffmpeg', ['-v', 'error', '-y', '-i', join(staging, 'render.mp4'), '-map', '0:v:0', '-c', 'copy', '-an', '-map_metadata', '-1', '-movflags', '+faststart', join(target, 'video.mp4')]);
const posterTime = uiProductTourChapters.find(step => step.id === 'commands')!.end - 3;
await exec('ffmpeg', ['-v', 'error', '-y', '-ss', String(posterTime), '-i', join(target, 'video.mp4'), '-frames:v', '1', join(staging, 'poster.png')]);
await sharp(join(staging, 'poster.png')).webp({ quality: 90 }).toFile(join(target, 'poster.webp'));
await writeFile(join(target, 'captions.vtt'), workflowCaptions(uiProductTourChapters.map(step => ({ ...step, caption: step.guide }))));
const time = (seconds: number) => `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`;
const transcript = `# Harakiri UI Product Tour\n\nA real, full-frame dashboard workflow. ${time(uiProductTourSeconds)} at 1920x1080. Silent video with optional English captions and a synchronized written guide.\n\nRecorded ${tour.capturedAt.slice(0, 10)} using a local source preview connected to the live Harakiri API. The source revision and file hashes are in provenance.json. This is a tested lab workflow, not a claim that every provider or installation supports identical runtime capabilities.\n\nThe small synthetic project uses Node 20, persistent storage and outbound policy enforcement. No model call or customer project is involved. Files were uploaded through the Harakiri API between the terminal and file-browser chapters. Provisioning and release waits between chapters are omitted; all recorded interactions remain at normal speed.\n\n${uiProductTourChapters.map(step => `## ${time(step.start)} - ${step.title}\n\n${step.guide}\n\n**Observed outcome:** ${step.outcome}\n`).join('\n')}\n## Reproduce\n\nDownload example-source.zip for README.md, check.mjs, server.mjs and prepare-tools.sh. The public documentation page at https://sb.harakiri.io/#docs/ui-product-tour contains the complete walkthrough and verification command.\n\n## Recording boundaries\n\nThe film is the entire application viewport, not browser chrome. No panel crops, zooms, time acceleration, fabricated output or paid model calls. Small pointer rings replay actual input positions. No voiceover is present. Native captions are optional because they overlay video; the synchronized guide sits outside the image.\n\nBoth tour runtimes were terminated and the route made inactive. The workspace was archived, not physically deleted. The temporary capture API key was revoked.\n`;
await writeFile(join(target, 'transcript.md'), transcript);
await writeFile(join(target, 'tutorial.html'), tourTutorialHtml());
await writeDemoIndex();
const fixture = join(workspace, 'fixtures/ui-product-tour');
for (const [name, hash] of Object.entries(tour.fixtureHashes)) assert.equal(await fileHash(join(fixture, name)), hash);
await exec('zip', ['-q', '-j', join(target, 'example-source.zip'), ...Object.keys(tour.fixtureHashes).map(name => join(fixture, name))]);
const files: Record<string, { sha256: string; bytes: number }> = {};
for (const name of ['video.mp4', 'poster.webp', 'captions.vtt', 'transcript.md', 'example-source.zip', 'tutorial.html']) files[name] = { sha256: await fileHash(join(target, name)), bytes: (await readFile(join(target, name))).length };
await writeJson(join(target, 'provenance.json'), { ...tour, seconds: uiProductTourSeconds, renderedAt: new Date().toISOString(), remotion: '4.0.520', framing: 'entire-application-viewport', narration: 'written-guide-and-optional-captions', annotations: 'actual-input-position-rings', waitingBetweenChaptersEdited: true, chapters: uiProductTourChapters.map(({ id, title, start, end }) => ({ id, title, start, end })), files });
console.log(`Rendered tour and published local assets (${(files['video.mp4']!.bytes / 1024 / 1024).toFixed(1)} MiB). Public deployment was not changed.`);
