import type { DemoStep } from './demo-walkthrough';

export const browserPromptLines = [
  'Read browser-app.html and write qa.mjs using playwright and node:assert/strict.',
  'The app is already running. Use process.env.BASE_URL as the target URL.',
  'Launch headless Chromium; always close it in finally. Do not start a server.',
  'At 1280x720, assert three visible release rows on load.',
  'Select Passed in the Status dropdown and assert only Portal is visible using node:assert immediately after selectOption; do not wait for expected row counts.',
  'Select All and assert the three rows return. Save desktop.png after restoring All.',
  'At 390x844, assert there is no horizontal page overflow and save mobile.png.',
  'Write qa-report.json with exactly initialRows:3, passedNames:["Portal"], restoredRows:3, mobileOverflow:false, using observed browser values.',
  'Do not modify browser-app.html, browser-server.mjs, package files or configuration.',
  'Do not mock Playwright, fabricate results or catch assertion failures to exit successfully.',
  'Use your tools to write and execute qa.mjs, then inspect the results.',
];

export const browserDemoSteps: DemoStep[] = [
  {
    id: 'use-case', title: 'Turn acceptance criteria into browser tests', chapter: 'Use case', seconds: 18,
    text: 'A preview build needs a regression check. Supply a small existing release-board app and ask OpenCode to write Playwright tests, execute them and return screenshots. The app is a deterministic fixture supplied by us; the test program is generated by the agent. This demonstrates test generation and execution, not a production CI integration.', language: "plaintext", code: '',
    check: 'The agent writes tests. The worker reruns them and checks they fail when the app filter is deliberately broken.',
  },
  {
    id: 'boundary', title: 'The browser runs inside the sandbox', chapter: 'Execution boundary', seconds: 18,
    text: 'Your Node worker coordinates via SDK 0.4.0. OpenCode, the fixture server and headless Chromium run in the same Harakiri sandbox. The agent contacts an external free model. No public route, desktop-control API, managed browser account or Kubernetes exec is used. This is a browser-QA example using current commands and files capabilities.', language: "plaintext", code: '',
    check: 'Only synthetic app source is provided to the model. No production site, credentials or customer browser session is involved.',
  },
  {
    id: 'setup', title: 'Run the complete worker example', chapter: 'Prerequisites and source', seconds: 20,
    text: 'Extract the source archive and open agent-workflows with Node.js 22+. Set HARAKIRI_API_URL and HARAKIRI_API_KEY privately. The ready opencode template used here allows package installation. Browser dependencies are not preinstalled in that stock template. On a restricted non-root runtime, an administrator must prebuild the dependencies into a template; do not change SCC or request privileged execution.',
    language: "bash", code: 'npm install @h-sandbox/sdk@0.4.0\nexport OPENCODE_MODEL=opencode/mimo-v2.5-free\nnode browser-qa.mjs',
    check: 'The downloadable example supplies the fixture, complete prompt, worker, artifact checks and cleanup. No paid model fallback.',
  },
  {
    id: 'acceptance', title: 'Set the contract before the agent starts', chapter: 'Fixture and expectations', seconds: 18,
    text: 'browser-app.html has three release rows. Its Status selector changes which rows are rendered. Expected behavior is three rows initially, Portal only after Passed, and three rows after All. The mobile viewport must not overflow horizontally. browser-server.mjs binds only to localhost. Source bytes are retained by the worker for later comparison.',
    language: "plaintext", code: 'Initial rows     Portal / Search / Billing\nPassed          Portal only\nAll             three rows restored\nDesktop         1280 x 720\nMobile          390 x 844 / no horizontal overflow',
    check: 'Expected results come from the caller. The agent receives an app and requirements, not a prewritten test suite.',
  },
  {
    id: 'install', title: 'Prepare Chromium in the remote workspace', chapter: 'Cold browser setup', seconds: 22,
    text: 'The worker creates an OpenCode sandbox with a 1200-second TTL and uploads the app plus explicit free main/small model configuration. It then installs pinned Playwright and its matching Chromium with a six-minute command budget. This needs outbound npm, browser-download and Debian package access. Cold installation time is real but edited out of the film. For repeated runs, bake these tools into a versioned template.',
    language: "bash", code: 'npm install --save-exact playwright@1.60.0\nnpx playwright install --with-deps chromium',
    check: 'These commands run inside the sandbox, not on your worker. Do not assume stock OpenCode includes a browser.',
  },
  {
    id: 'server', title: 'Start a tracked server, then check readiness', chapter: 'Start the fixture', seconds: 20,
    text: 'Keep the Node server as its own detached tracked command. Do not launch it as an orphan from a short-lived command and assume it survives. The worker polls the local /health URL before starting the agent. No port is exposed publicly; the agent and Chromium use sandbox-local networking.',
    language: "javascript", code: `await client.commands.start(sandbox.id, {
  command: 'node browser-server.mjs', cwd: '/workspace',
  timeoutMs: 600000, detached: true,
});
// Check inside the sandbox before starting the agent:
// curl --fail http://127.0.0.1:3000/health`,
    check: 'The local health check must succeed. Detached returns a job handle, not a ready application.',
  },
  {
    id: 'prompt-actions', title: 'The full prompt: browser interactions', chapter: 'Full prompt: interactions', seconds: 24,
    text: 'The first six lines of browser-prompt.txt specify actual Playwright assertions, a configurable target, guaranteed browser cleanup and the exact filter interactions. This is a coding agent writing a browser test, not a model controlling a virtual desktop with screenshots.', language: "plaintext", code: browserPromptLines.slice(0, 6).join('\n'),
    check: 'The agent must observe real rows, select Passed, restore All and capture the result in Chromium.',
  },
  {
    id: 'prompt-outputs', title: 'The full prompt: artifacts and guardrails', chapter: 'Full prompt: artifacts', seconds: 24,
    text: 'The remaining five lines request mobile checks and files derived from observed browser state. An instruction not to modify the app is not a security boundary; the worker checks its bytes afterward. Mutation testing provides additional evidence that the generated suite does not merely print the expected answer.', language: "plaintext", code: browserPromptLines.slice(6).join('\n'),
    check: 'The prompt names every output and forbids fabricated results. The worker still independently checks acceptance.',
  },
  {
    id: 'agent', title: 'Build and execute the agentCommand', chapter: 'Run and wait', seconds: 22,
    text: 'The worker reads the complete prompt file. shellQuote makes it one literal shell argument. run is a local helper in browser-qa.mjs wrapping commands.start, commands.wait and commands.logs with explicit budgets. It is not a hidden SDK agent method. Both free-model step costs and completed tool states are checked before accepting files.',
    language: "javascript", code: `const prompt = (await readFile(
  new URL('./browser-prompt.txt', import.meta.url), 'utf8'
)).trim();
const shellQuote = (value) => "'" + value.replaceAll("'", "'\\\\''") + "'";
const agentCommand =
  \`opencode run --format json --model \${model} \${shellQuote(prompt)}\`;
const agent = await run(
  \`BASE_URL=http://127.0.0.1:3000 \${agentCommand}\`, 240000
);`,
    check: 'The four-minute agent command runs in /workspace. Raw reasoning stays private; only reviewed evidence is published.',
  },
  {
    id: 'generated-test', title: 'Inspect the assertion OpenCode actually wrote', chapter: 'Agent-written test', seconds: 20,
    text: 'The film shows an excerpt from the real generated qa.mjs, not a suggested test pasted in by the worker. OpenCode used Playwright to select the filter, read the rendered names and compare them with Portal. Review the complete generated test in browser-output/qa.mjs after your own run; implementations can vary.', language: "plaintext", code: '',
    check: 'The recorded assertion reads browser state. The later mutation check proves it rejects the extra visible rows.',
  },
  {
    id: 'rerun', title: 'Independently rerun the generated tests', chapter: 'Fresh verification', seconds: 20,
    text: 'After generation, the worker verifies unchanged app source, retains the generated qa.mjs and deletes the old report/screenshots. It runs the generated test itself and requires fresh artifacts. The JSON object must match the exact expected values and types. This separates process success from actual acceptance.',
    language: "bash", code: 'rm -f qa-report.json desktop.png mobile.png\nBASE_URL=http://127.0.0.1:3000 node qa.mjs',
    check: 'Fresh artifacts must be created. Existing output from the agent run cannot satisfy the independent rerun.',
  },
  {
    id: 'desktop', title: 'Retrieve the real desktop screenshot', chapter: 'Desktop artifact', seconds: 18,
    text: 'files.download transfers desktop.png from the remote sandbox as contentBase64. The worker writes decoded bytes into browser-output. The film displays that downloaded image, not a generated mockup. The capture checks PNG dimensions and nonblank pixels; assertions validate behavior separately.', language: "plaintext", code: '',
    check: 'A real 1280 x 720 Chromium screenshot, downloaded through the Harakiri SDK after the independent run.',
  },
  {
    id: 'mobile', title: 'Check the mobile viewport too', chapter: 'Mobile artifact', seconds: 18,
    text: 'The same generated suite uses a 390 x 844 viewport and checks document width against viewport width. mobile.png is downloaded before termination. This is a focused overflow test at one viewport, not a comprehensive accessibility or cross-browser audit.', language: "plaintext", code: '',
    check: 'Real 390 x 844 screenshot. The generated test reports no horizontal overflow for this fixture.',
  },
  {
    id: 'mutation', title: 'Break the filter and require a failing test', chapter: 'Mutation test', seconds: 24,
    text: 'Only after the agent finishes, the worker creates a second fixture whose filter always returns every row. It starts this copy on local port 3001 and runs exactly the same qa.mjs with BASE_URL changed. commands.wait explicitly accepts failed terminal states so the worker can inspect the expected failure rather than treating it as an unexpected exception.',
    language: "bash", code: `// Target the broken copy with the unchanged generated suite:
BASE_URL=http://127.0.0.1:3001 node qa.mjs

// The worker requires:
// nonzero exitCode AND AssertionError / ERR_ASSERTION
// identical qa.mjs bytes before and after verification`,
    check: 'A browser startup error is not accepted as regression detection. The broken filter must trigger an assertion failure.',
  },
  {
    id: 'result', title: 'Accept evidence, not a green agent message', chapter: 'Verified outcome', seconds: 20,
    text: 'The fixture passed the independent run and the deliberate regression was rejected. The original app and generated test remained unchanged. The downloadable worker saves qa.mjs, qa-report.json, desktop.png and mobile.png locally. This small mutation check increases confidence but does not prove exhaustive coverage or resist a malicious test author.', language: "plaintext", code: '',
    check: 'Original app passes. Broken filter fails. Screenshots downloaded. Model steps reported zero cost in this run.',
  },
  {
    id: 'cleanup', title: 'Terminate both servers with the sandbox', chapter: 'Cleanup and failures', seconds: 20,
    text: 'The worker uses try/finally to kill the sandbox and wait for terminated on success or failure. Both local servers and Chromium belong to that runtime. If the worker loses network access or is killed, retain its printed sandbox ID and recover with inspect/kill; the 1200-second TTL is a fallback. The example does not post comments or upload artifacts to any external CI service.',
    language: "javascript", code: `finally {
  await client.killSandbox(sandbox.id);
  await client.waitForSandbox(sandbox.id, {
    statuses: ['terminated'], timeoutMs: 30000,
  });
}`,
    check: 'The capture independently confirms termination. Setup failures, unavailable models and failed assertions also require cleanup.',
  },
];

export const browserDemoTutorial = {
  id: 'browser-agent-qa', title: 'SDK: generate and verify browser tests',
  lede: 'OpenCode writes Playwright tests for a synthetic preview app. Run Chromium inside Harakiri, retrieve real desktop/mobile screenshots and reject a deliberately broken filter.',
  sections: browserDemoSteps,
};
