export const uiProductTourSteps = [
  { id: 'orientation', title: 'One project, one control plane', seconds: 12,
    guide: 'Harakiri is a self-hosted sandbox control plane for agent applications. This is the real dashboard, at normal browser zoom. Follow a release-check project from environment selection to verified cleanup. The example is deterministic: no model account or AI-generated output is needed.',
    outcome: 'The full application navigation and sandbox inventory remain visible.' },
  { id: 'templates', title: 'Choose the environment', seconds: 18,
    guide: 'Templates describe the environment your work runs in. Compare CPU, memory, visibility and readiness before launching. This project uses Node 20, with one CPU and 1 GiB of memory. Other agent-specific examples live in the demo library; this tour focuses on the control plane itself.',
    outcome: 'A ready Node 20 template is selected, without building a new image.' },
  { id: 'workspace', title: 'Give the project durable storage', seconds: 18,
    guide: 'A workspace is persistent project storage, not another running sandbox. Create release-checks once. Its files will be mounted at /workspace when a sandbox attaches. This installation allocates 1 GiB; storage size and availability depend on the operator configuration.',
    outcome: 'The new workspace is Available, with no runtime attached.' },
  { id: 'launch', title: 'Launch with explicit limits', seconds: 22,
    guide: 'Create a sandbox from the workspace. Choose Node 20, name the runtime release-checks-01, and set a 30-minute lifetime for recording. Resources come from the template. Internet access starts enabled. Provisioning may take longer than shown: only waiting between chapters is removed.',
    outcome: 'The sandbox is created with the selected template and workspace.' },
  { id: 'terminal', title: 'Connect to the real runtime', seconds: 18,
    guide: 'The sandbox detail view keeps status, lifetime, template and workspace together. Terminal connects through Harakiri. Run pwd and node --version to inspect the actual environment. Commands and outputs in this film are executed, not reconstructed. There is no Kubernetes exec fallback.',
    outcome: 'The terminal responds with the working directory and installed Node version.' },
  { id: 'tools', title: 'Prepare the connectivity tools', seconds: 24,
    guide: 'The example files were uploaded through the file API between chapters. This minimal Node image needs curl and certificate roots for the built-in access test. Run the included prepare-tools.sh through Commands while Internet access is enabled. Package output is retained in /tmp/tour-packages.log. A prepared team template can include these tools already.',
    outcome: 'curl and trusted certificate roots are installed in this disposable runtime.' },
  { id: 'files', title: 'Inspect the project files', seconds: 16,
    guide: 'The four small example files are included with this tour. Filesystem shows the runtime directory listing, sizes and paths. Open /workspace to inspect the project. This view is a browser, not an in-browser code editor. The release check will create a report alongside these files.',
    outcome: 'README.md, check.mjs and server.mjs are visible in /workspace.' },
  { id: 'commands', title: 'Run work with retained output', seconds: 28,
    guide: 'Use Commands for tracked work. Set the working directory explicitly and run node check.mjs. The script validates three release checks and writes report.json. Output arrives while the command runs, and the exit code makes completion explicit. This is a deterministic test fixture, not an agent benchmark.',
    outcome: 'Three checks pass, report.json is written, and the command exits with code 0.' },
  { id: 'reconnect', title: 'Return to the same command', seconds: 16,
    guide: 'Move to Filesystem to see the new report, then return to Commands and select the same run. Its output can be followed again without starting duplicate work. Command history belongs to the runtime; it is not a promise of permanent log retention after that runtime is deleted.',
    outcome: 'The existing command output is replayed; the command is not rerun.' },
  { id: 'server', title: 'Start a preview service', seconds: 18,
    guide: 'Start node server.mjs from Commands. It serves the report on port 3000 and binds to all sandbox interfaces. The process continues when you move to another tab. The UI gives tracked commands a five-minute command timeout, so this preview is deliberately short-lived.',
    outcome: 'The service reports that port 3000 is ready.' },
  { id: 'preview', title: 'Share a running result', seconds: 20,
    guide: 'In Network, expose port 3000 as a Public route and open the resulting URL. This example contains only synthetic release-check results. Public means anyone with the URL can visit it; use Token access for a protected service. The preview below is the actual running server, not a screenshot mockup.',
    outcome: 'The live preview returns the report containing three passing checks.' },
  { id: 'egress', title: 'Control outbound access', seconds: 28,
    guide: 'Inbound previews and outbound policy solve different problems. Select the Node packages preset. The package registry is reachable; example.com is not after the restriction. The capture verified that example.com was reachable before the change. Counters represent rules, not traffic totals. These tests execute inside the sandbox.',
    outcome: 'The permitted registry is reachable. The previously reachable, unlisted site is now blocked or unreachable.' },
  { id: 'inspect', title: 'Inspect runtime activity', seconds: 18,
    guide: 'Logs and Metrics keep runtime diagnostics near the work. Inspect lifecycle entries, then the current CPU and memory snapshot. These are operational observations, not historical billing data or an agent-reasoning trace. Provider capabilities determine which additional runtime measurements are available.',
    outcome: 'Real lifecycle logs and a CPU/memory snapshot are returned.' },
  { id: 'release', title: 'End compute, keep the project', seconds: 14,
    guide: 'Kill terminates this sandbox and its preview route. It does not erase a persistent workspace. Wait for the workspace to finish releasing before reusing it. The next chapter begins after that release has completed; no concurrent writer or instant handoff is implied.',
    outcome: 'The first runtime is terminated and its workspace becomes Available.' },
  { id: 'replacement', title: 'Start a replacement runtime', seconds: 22,
    guide: 'Return to Workspaces and create release-checks-02 from the same storage. Choose Node 20 again. This is a new sandbox, not a resumed process or a VM snapshot. The project files are retained; processes, open connections and command history are not carried over.',
    outcome: 'A different sandbox attaches to the original workspace.' },
  { id: 'verify', title: 'Prove the files survived', seconds: 22,
    guide: 'In the replacement sandbox, run the report verification command from /workspace. It reads the existing report.json and verifies that all three checks passed. The capture also compares the report bytes across both runtimes. Nothing regenerates the report during this verification.',
    outcome: 'The retained report passes verification in a new runtime, with identical contents.' },
  { id: 'cleanup', title: 'Finish with visible cleanup', seconds: 20,
    guide: 'Terminate the replacement runtime and archive the workspace. The archive dialog explicitly retains its files and storage allocation; physical deletion is an operator action. Both runtimes and the preview are now inactive. Continue with the CLI, SDK and OpenCode demos for real agent workflows on the same control plane.',
    outcome: 'No tour runtime is running. The workspace is archived with files retained.' },
] as const;

let elapsed = 0;
export const uiProductTourChapters = uiProductTourSteps.map((step) => {
  const start = elapsed;
  elapsed += step.seconds;
  return { ...step, start, end: elapsed };
});
export const uiProductTourSeconds = elapsed;
