{{- if .Values.harborPullSecret.create }}
{{- $reg := .Values.harborPullSecret.registry -}}
{{- $user := .Values.harborPullSecret.username -}}
{{- $pass := .Values.harborPullSecret.password -}}
{{- $email := .Values.harborPullSecret.email -}}
{{- $auth := printf "%s:%s" $user $pass | b64enc -}}
{{- $dockercfg := dict "auths" (dict $reg (dict "username" $user "password" $pass "email" $email "auth" $auth)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.harborPullSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harakiri.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockercfg | toJson | b64enc }}
{{- end }}
