{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-api" (include "harakiri.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harakiri.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
