apiVersion: v1
kind: Service
metadata:
  name: {{ include "harakiri.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harakiri.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "harakiri.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "harakiri.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harakiri.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "harakiri.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
{{- if .Values.registry.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "harakiri.fullname" . }}-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harakiri.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
spec:
  selector:
    {{- include "harakiri.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: registry
  ports:
    - name: http
      port: {{ .Values.registry.port }}
      targetPort: registry
{{- end }}
