apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace.yaml
  - postgres/postgres.yaml
  - keycloak/keycloak.yaml
  - harakiri/harakiri.yaml
  - opensandbox/harakiri-exec-rbac.yaml
  - opensandbox/opensandbox-server-diagnostics-rbac.yaml
  - opensandbox/sandbox-gateway-rbac.yaml
  - opensandbox/sandbox-wildcard-ingress.yaml
